#!/bin/bash
#PBS -q normal
#PBS -N NGBW-JOB-MAFFT_TG-5A964DCD04E241EF8B43F6906D0CD0A9
#PBS -l walltime=00:180:00
#PBS -l epilogue=/projects/ps-ngbt/backend/gordon_workspace/NGBW-JOB-MAFFT_TG-5A964DCD04E241EF8B43F6906D0CD0A9/epilogue.sh
#PBS -o scheduler_stdout.txt
#PBS -e scheduler_stderr.txt
#PBS -W umask=0007

##PBS -V

#PBS -v QOS=5

#PBS -M  terri@sdsc.edu,mmiller@sdsc.edu
#PBS -m ae
#PBS -A TG-DEB090011
#PBS -l nodes=1:ppn=16:noflash
cd /projects/ps-ngbt/backend/gordon_workspace/NGBW-JOB-MAFFT_TG-5A964DCD04E241EF8B43F6906D0CD0A9

source /etc/profile.d/modules.sh



date +'%s %a %b %e %R:%S %Z %Y' > start.txt

curl -k https://www.phylo.org/portal2/taskupdate.action?taskId=647502\&jh=NGBW-JOB-MAFFT_TG-5A964DCD04E241EF8B43F6906D0CD0A9\&status=START

export CIPRES_THREADSPP=8
export CIPRES_NP=1

./batch_command.cmdline 1>stdout.txt 2>stderr.txt
retval=$?

date +'%s %a %b %e %R:%S %Z %Y' > done.txt
qstat -f $PBS_JOBID | grep Job
qstat -f $PBS_JOBID | grep resources
curl -k https://www.phylo.org/portal2/taskupdate.action?taskId=647502\&jh=NGBW-JOB-MAFFT_TG-5A964DCD04E241EF8B43F6906D0CD0A9\&status=DONE
exit $retval